# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    packages:
      - google-chrome-stable

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true
  directories:
    - "node_modules"

notifications:
  email: false

deploy:
  api_key:
    secure: UPVF4frP8MNT+4qQ5qwdOl+xHBofE5EDcCU+bdT8kE9JjeZFuzYg3U9Tz/XU4RvMLxa5bC9sQzbJCDuOZI9ZCciz3qlw4jWdrlyMFHlcnG7IxoJw7CrO56f4aAkv1Z/rNdNKr21o3O2oEBnhKTx2e6LADdJlTwlhiX+hKNcniEqiNw1RrKrdQFsj7inLw5bO+yCbuGGafjqA7SN4bP+NL5oKMB4WNG6xctdi7klUXWtX1dwo2aiIha9f06H5Ia4+Il6ZLEznaIebdkeXbMPUoHmSXbPqNoal/4srFqqtfWhtYEWzqdD7PwtFEWpUQ09CyVLpcemBBDHWvQCVxT+OpD48ofZm3/0lg3S7v7YBryz3R93LSiXz+Qn+qaG+Rr0w8xCndHvqbNTAsoUJ51RjiBssjzH6Hfnx5g1Tszj/kuPbsjwBjoVjFqG74sbemhj5qvm2SuC3Wy2j7j4H7G8YpanHBfhN0g9C9o+HD0Hn4r3jahSVBU/e1mLiQU96U85k1oACljx+DnXBqgnh0naSkzI5SneqWjlAL686rOqoyaaEzl8bwKBhjefrb6DovUR093ZM0DT6aQfcDZwgIWXhKAapLdUU0kP3zVrOi7BjZ9cDiTe0oVOgPNRC63/s0Uano4M7aT8VC4+xbTky6V9ax1g8LpW8DCRFw/nNQSCI5Yo=
  email:
    secure: lDonWZYjxRDA67KhyrEaLpVNRg32CRsksDztCfBDkkLSd3pzdmsYP+ll/brom1VOAGbUq9KmkwdX2uTOPgzd4GHfROMGhkIvltFK8ZbPyVXrofuMMUkj+dhDCARd4cjsJkM+yLHlqM+bnIrQrxtz3WFiy5sKvYpMM3xr5+uDZIIO/BqvIzaDvntdyAG1rTWRIEZyVWy5qleltD2UunaXhmYW+vGJv1nJg6suLOY3oFAhb6Xz91psiS/Nw6gCNmQ8hBVbqLMIcZiKpVG4GM7rmg+j6k4DGu2QjWcU/n3Hl/BANgnu/QERQFA0RLbMR9poQpO2SwisJKOPQ/EXEPwwqydkUllUVHTsFa8tMus/APpb9yyRhdFHPXcQ7j0YkKNmr4GVj2MHHeFQaJqpB7rF1r96OdEehrAn8gwXofB8WUwxDap5mP8l+EkkFbfalxpXXzHffJHL06DHG5d9+tDRe7Fr1Bqitu2ZE73/VSttjR5OjfChIAHEFSfiK/KkjDiGJu1MHZw12YJk64ZLxLtRhEVB/pvw1c2NZYYGysGxuwZNMrSPmwaYwsvM1EJkSFTOk6zXaj4dXGe/ttUo1JMLCvH7zpdngFIVXOWWoyw0vrsaWwHsoGLjMC6cQGdVOG1m85gzef2VOAxhstc6nHGH6axvHpPSRAufYOmDcrvhr2c=
  provider: npm
  skip_cleanup: true
  on:
    tags: true
